Feature/add contact
eltonls/agenda-vue pull request #3
Opened 2024-06-10 20:03 UTC by riquealuno08

2024-06-10 21:35 UTC, VictoriaRSsousa approved these changes

2024-06-11 10:53 UTC, eltonls requested changes
Your code should be written in english, but you have a method written in portuguese. Please, change it and solve the conflicts.

2024-06-11 16:44 UTC, riquealuno08 reviewed
AddContact Update

2024-06-11 17:18 UTC, eltonls approved these changes
Approve!

2024-06-11 17:18 UTC, merged